"""your description

Revision ID: daf5782f6d11
Revises: 9e96afce0c9e
Create Date: 2023-03-16 08:55:30.155537

"""

# revision identifiers, used by Alembic.
revision = "daf5782f6d11"
down_revision = "9e96afce0c9e"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
